plugins {
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
}

group = 'com.nirmatacipher.questdumper'
version = '1.0.0'

java {
    toolchain.languageVersion = JavaLanguageVersion.of(17)
}

minecraft {
    mappings channel: 'official', version: '1.20.1'
}


repositories {
    maven { url = 'https://maven.minecraftforge.net/' }
    mavenCentral()
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.1-47.4.20'
}

jar {
    manifest {
        attributes([
            'Specification-Title'     : 'Arcanum Quest Dumper',
            'Specification-Vendor'    : 'NirmataCipher',
            'Specification-Version'   : '1',
            'Implementation-Title'    : project.name,
            'Implementation-Version'  : project.version,
            'Implementation-Vendor'   : 'NirmataCipher'
        ])
    }
}
